### ISSUE TITLE
Netlify doesn't allow CORS by default

### ISSUE THREAD

**Issue by D-Limonene** [twikoojs/twikoo-netlify#2]
When my twikoo plugin tries to communicate with the backend, the browser reports:

> Access to XMLHttpRequest at '\<netlify-backend\>' from origin '\<my-blog\>' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
> ...
> \<similar blablabla\>

By referring to [a typical CORS setting by Cloudflare](https://developers.cloudflare.com/pages/functions/examples/cors-headers/) and [this StackOverflow post](https://stackoverflow.com/questions/62507022/how-to-enable-cors-on-a-netlify-deployment), I'm creating a pull request fixing it.

**Comment by imaegoo** [comment]
Please check your `envId`. This is usually caused by the wrong `envId` Settings

```diff
-Wrong:
-https://xxx.netlify.app
-https://xxx.netlify.app/
+Right:
+https://xxx.netlify.app/.netlify/functions/twikoo
```

**Comment by D-Limonene** [comment]
> Please check your `envId`. This is usually caused by the wrong `envId` Settings
> 
> ```diff
> -Wrong:
> -https://xxx.netlify.app
> -https://xxx.netlify.app/
> +Right:
> +https://xxx.netlify.app/.netlify/functions/twikoo
> ```

Sounds reasonable, I'm having a try

**Comment by D-Limonene** [comment]
I think you are correct, sorry for bothering. :)
